apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-todo-app
  template:
    metadata:
      labels:
        app: flask-todo-app
    spec:
      containers:
      - name: flask-todo-app
        image: sonu10/todo-flask-app
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: todo-persistent-storage
          mountPath: /instance
      volumes:
      - name: todo-persistent-storage
        azureFile:
          secretName: azure-secret
          shareName: todo
          readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  name: flask-todo-app-service
spec:
  type: LoadBalancer
  selector:
    app: flask-todo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
