name: Deploy to AKS

on:
  push:
    branches:
      - main  
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up kubectl
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: ${{ secrets.AZURE_AKS }}
        resource-group: ${{ secrets.AZURE_RG }}

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      env:
        IMAGE_NAME: "todo-flask-app"  # Define the image name
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    - name: Deploy to AKS
      run: |
        kubectl apply -f deployment.yml
